include: ["keybase.txt"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/index.html
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-seo-tag
